version: '3'
services:
  smokeping-master:
    image: sarstw/smokeping-docker:ubuntu19.10-2.7.3-master
    container_name: smokeping-master
    hostname: master
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/default
      - ./config.d/Database:/etc/smokeping/config.d/Database
      - ./config.d/Probes:/etc/smokeping/config.d/Probes
      - ./config.d/Slaves:/etc/smokeping/config.d/Slaves
      - ./config.d/Targets:/etc/smokeping/config.d/Targets
        #- ./smokeping_data:/var/lib/smokeping

  smokeping-slave:
    image: sarstw/smokeping-docker:ubuntu19.10-2.7.3-slave
    container_name: smokeping-slave
    restart: unless-stopped
    environment:
      - MASTER_URL=http://smokeping-master/smokeping/
      - SLAVE_NAME=host2
      - SECRET=yoursercert
      - TZ=Asia/Taipei

