FROM ubuntu:19.10

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get install -y tzdata ca-certificates nginx smokeping spawn-fcgi supervisor \
    && apt-get clean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV TZ=Asia/Taipei
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ADD supervisord-smokeping.conf /etc/supervisor/conf.d/smokeping.conf
ADD supervisord-fcgi.conf /etc/supervisor/conf.d/fcgi.conf
ADD supervisord-nginx.conf /etc/supervisor/conf.d/nginx.conf

RUN mkdir -p /var/run/smokeping /var/lib/smokeping/__cgi/Local/
RUN chown -R smokeping:www-data /var/run/smokeping /var/lib/smokeping
RUN chmod -R 777 /var/cache/smokeping /var/lib/smokeping
RUN mv /usr/share/smokeping/www/smokeping.fcgi.dist /usr/share/smokeping/www/smokeping.fcgi

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]

