FROM debian:10.0-slim

RUN apt-get update -y && apt-get install -y nginx smokeping spawn-fcgi supervisor \
    && apt-get clean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD supervisord-smokeping.conf /etc/supervisor/conf.d/smokeping.conf
ADD supervisord-fcgi.conf /etc/supervisor/conf.d/fcgi.conf
ADD supervisord-nginx.conf /etc/supervisor/conf.d/nginx.conf

RUN mkdir -p /var/run/smokeping
RUN chown smokeping:smokeping /var/run/smokeping
RUN chmod -R 777 /var/cache/smokeping
RUN mv /usr/share/smokeping/www/smokeping.fcgi.dist /usr/share/smokeping/www/smokeping.fcgi

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]

